### PR TITLE
Making latexmkrc compatible with older versions

### PR DESCRIPTION
**Pull request by jorgefandinno**
It seems that old versions of latexmk do not have the function "ensure_path()'.
In that case, this patch resorts to set the variable directly.
In particular, this problem affects Pedro.
Probably the current patch will not work on old versions of latexmk running on Windows, but it seems to work on old versions on latexmk on Linux and MacOs and it should work on all new version of latexmk independently of the platform.

### CODE REVIEW

**Comment by tortinator** [comment]
Hi @rkaminsk, since @jorgefandinno hasn't assigned it to anybody, would you mind taking a look? Gracias!

**Comment by rkaminsk** [comment]
@jorgefandinno, does the last commit work for you?

**Comment by rkaminsk** [comment]
Having the synctex option in the pdf might reveal your username. So be careful in double blind reviews.

**Comment by jorgefandinno** [comment]
Please check the last commit.

$ENV{'TEXMFHOME'} = '?';

does not work in some platforms. 

That this work for you?

I will also need to check with Pedro, he was the one having  problems.

**Comment by rkaminsk** [comment]
The only thing `ensure_path` does is append a `;` or `:` depending on the platform. On *nixes this should amount to
```perl
$ENV{'TEXMFHOME'} = '?:';
```
and on Windows:
```perl
$ENV{'TEXMFHOME'} = '?;';
```

Furthermore, `ensure_path` prepends to the path. The idea was to reset the path, so just prepending a `?` is not what we want. I am a bit at a loss to review this without concrete error messages.

EDIT: If just the question mark symbol is the problem, we can also use a randomly generated string that is unlikely to ever collide with a real directory name. But I still don't know what the actual problem is.

**Comment by jorgefandinno** [comment]
Ok, I reverted the change. I will ask Pedro to check if all works for him.

**Comment by rkaminsk** [comment]
I know for sure that colons in filenames are causing trouble on Windows. This was also the reason why I merged your first PR.

**Pull request merged**
